---
- name: Add the Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
 
- name: Install Docker Prerequisite packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - yum-utils

- name: Install the Docker
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io
  - docker-compose

- name: create docker group
  group:
    name: docker
    state: present

- name: Add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Start docker
  service:
    name: docker
    state: started

- name: Enable docker
  service:
    name: docker
    enabled: yes