---

- name: Add the epel-release
  yum:
    name: epel-release
    state: latest

- name: Install the git
  yum:
    name: git
    state: latest

- include_tasks: disable-swap.yml

- include_tasks: syctl-setup.yml

- include_tasks: install-docker.yml

- include_tasks: k8srepo-setup.yml

- include_tasks: install-k8s.yml

- include_tasks: create_cluster.yml