---
- name: install k8s(kubelet, kubeadm, kubectl)
  yum:
    name: "{{ item }}"
    state: present
    disable_excludes: 'kubernetes'
  with_items:
  - kubelet
  - kubeadm
  - kubectl
  notify: restart kubelet

# - name: Configure node ip
#   lineinfile:
#     create: yes
#     path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
#     line: Environment="KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }}"
