---
- name: Check if already joind
  stat:
    path: /etc/cni
  register: kubernetes_init_stat

- name: Copy the join command to server location
  copy: 
    src: join-command
    dest: /home/vagrant/join-command.sh
    mode: 0755
  when: not kubernetes_init_stat.stat.exists

- name: Join the node to cluster
  command: sh /home/vagrant/join-command.sh
  when: not kubernetes_init_stat.stat.exists