---
- name: configure ansible hosts
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: create hosts and configuration
      copy:
        dest: /home/vagrant/hosts
        content: |
          [master]          
          192.168.25.221

          [master:vars]
          ansible_python_interpreter=/usr/bin/python3

          [worker]
          192.168.25.223
          192.168.25.224

          [worker:vars]
          ansible_python_interpreter=/usr/bin/python3
          