---
- name: configure ansible hosts
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: create hosts and configuration
      copy:
        dest: /home/vagrant/hosts
        content: |
          [master]
          172.16.10.200

          [worker]
          172.16.10.11