---
# k8s repositories
kubernetes_yum_arch: x86_64
kubernetes_yum_base_url: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ kubernetes_yum_arch }}"
kubernetes_yum_gpg_key:
- https://packages.cloud.google.com/yum/doc/yum-key.gpg
- https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

# k8s CNI
# sepcific version
# calico_url: "https://docs.projectcalico.org/v3.9/manifests/calico.yaml"

# latset version
calico_url: "https://docs.projectcalico.org/manifests/calico.yaml"

# pod cidr
pod_cidr: "172.16.0.0/16"

# cluseter_name
node_name: "control-plane-1"

# kubeconfig copy location
kubeconfig_location: "/root/.kube"
kubeconfig_chown: "root"

# join command to file location
join_command_location: "/home/vagrant/ansible_workspace/roles/k8s_worker/worker/files/join-command"